### ISSUE TITLE
Add authenticated service call example

### ISSUE THREAD

**Issue by sopelt** [Tirasa/olingoClientOnAndroidSample#2]
I am attempting to use olingo on android to access a .NET/WebAPI based ODATA V3 service. (Olingo seems to be the best option ... I failed using odata4j and restlet and olingo seems to be very active). Our service uses JWT bearer tokens in headers and (as a fallback) basic authentication. Could you enhance the example by adding a simple request against an authorized service?

Based on your example I tried adding the following just before the metadata request:

`client.getConfiguration().setHttpClientFactory(new BasicAuthHttpClientFactory("...", "..."));`

but I keep getting _(401) Unauthorized [HTTP/1.1 401 Unauthorized]_

Thank you for your work on this sample and olingo!

**Comment by ilgrosso** [comment]
Thanks for your words!

First of all, since you are using an OData V3 service, be sure to change

``` java
ODataClientFactory.getV4()
```

with

``` java
ODataClientFactory.getV3()
```

and all imports accordingly.

About the way to set the basic authentication, the one reported above looks correct; in order to add an authenticated service call, I would need a public accessible service, but I don't think there is one like this.

**Comment by sopelt** [comment]
Thank you for your swift reply. After you confirmed that using the factory was the right way to go I had another close look and the issue seems to have been with our service. We did not correctly set a basic realm which caused HttpClient to not send authentication at all. I guess this could be interpreted as being more strict as none of the browsers and other odata SDKs we tested behaved that way.

As you suspected I was unable to find any public odata test-services with authentication so I guess extending this example does not really make sense.

Is there any documentation on what `getV3` vs `getEdmEnabledV3` actually means or should I just checkout the source? :)

**Comment by ilgrosso** [comment]
> Is there any documentation on what getV3 vs getEdmEnabledV3 actually means or should I just checkout the source? :)

Eh eh eh, documentation for Olingo 4 has still to be built (hey, would you lend a hand?).

Basically, `getEdmEnabledV3` returns a client instance that will first query the OData service for Edm metadata and that will keep such information in memory while parsing any further response from the service. If you are working with Atom or JSON (full metadata) this is not particularly useful, but for JSON (minimal metadata) it allows to save some space during the conversation.
Beware that this feature was primarily meant for V4, so you might experience some misbehavior.
